# Generated by Django 5.0.6 on 2024-06-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('id_number', models.PositiveSmallIntegerField()),
                ('years_of_experience', models.PositiveSmallIntegerField()),
                ('nationality', models.CharField(max_length=20)),
                ('coutry', models.CharField(max_length=20)),
            ],
        ),
    ]
